# Generated by Django 2.2.5 on 2019-10-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20191017_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='descripcion',
            field=models.CharField(max_length=82),
        ),
    ]
